"""add_audit_fields_to_evaluations_and_projects

Revision ID: 068035fe33ba
Revises: b2bbebabf911
Create Date: 2025-12-16 08:26:46.243696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068035fe33ba'
down_revision: Union[str, Sequence[str], None] = 'b2bbebabf911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
