"""Add job tracking fields

Revision ID: 3e656b0436fd
Revises: 87b38e4b843e
Create Date: 2025-11-30 23:12:50.321431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3e656b0436fd'
down_revision: Union[str, Sequence[str], None] = '87b38e4b843e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'completed_at')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'error_message')
    op.drop_column('jobs', 'celery_task_id')
    # ### end Alembic commands ###
