"""add refresh tokens and gdpr fields

Revision ID: 8ffae68830a0
Revises: 9fce5ed48cf9
Create Date: 2025-12-15 21:26:21.421204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8ffae68830a0'
down_revision: Union[str, Sequence[str], None] = '9fce5ed48cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('replaced_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_table('usage_records')
    op.drop_table('quotas')
    op.drop_table('artifacts')
    op.alter_column('email_verification_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('email_verification_tokens_user_id_fkey'), 'email_verification_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'email_verification_tokens', 'users', ['user_id'], ['id'])
    op.alter_column('exports', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('exports', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('exports', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('exports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_exports_created_by'), 'exports', ['created_by'], unique=False)
    op.create_index(op.f('ix_exports_dataset_id'), 'exports', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_exports_generator_id'), 'exports', ['generator_id'], unique=False)
    op.create_index(op.f('ix_exports_project_id'), 'exports', ['project_id'], unique=False)
    op.create_foreign_key(None, 'exports', 'datasets', ['dataset_id'], ['id'])
    op.create_foreign_key(None, 'exports', 'generators', ['generator_id'], ['id'])
    op.create_foreign_key(None, 'exports', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'exports', 'projects', ['project_id'], ['id'])
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('tos_accepted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('privacy_accepted_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_2fa_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'totp_secret_encrypted',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('users', 'is_phone_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('uq_users_oauth_provider_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_users_oauth_provider_id'), 'users', ['oauth_provider', 'oauth_id'], unique=True)
    op.alter_column('users', 'is_phone_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'totp_secret_encrypted',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'is_2fa_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('users', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_column('users', 'privacy_accepted_at')
    op.drop_column('users', 'tos_accepted_at')
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('password_reset_tokens_user_id_fkey'), 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_constraint(None, 'exports', type_='foreignkey')
    op.drop_constraint(None, 'exports', type_='foreignkey')
    op.drop_constraint(None, 'exports', type_='foreignkey')
    op.drop_constraint(None, 'exports', type_='foreignkey')
    op.drop_index(op.f('ix_exports_project_id'), table_name='exports')
    op.drop_index(op.f('ix_exports_generator_id'), table_name='exports')
    op.drop_index(op.f('ix_exports_dataset_id'), table_name='exports')
    op.drop_index(op.f('ix_exports_created_by'), table_name='exports')
    op.alter_column('exports', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('exports', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('exports', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('exports', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.drop_constraint(None, 'email_verification_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('email_verification_tokens_user_id_fkey'), 'email_verification_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('email_verification_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('artifact_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size_bytes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('artifacts_job_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('artifacts_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('artifacts_pkey'))
    )
    op.create_table('quotas',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quota_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('limit_val', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reset_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('quotas_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quotas_pkey'))
    )
    op.create_table('usage_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('usage_records_project_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('usage_records_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('usage_records_pkey'))
    )
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
