"""add_audit_fields_to_evaluations_and_projects

Revision ID: b2bbebabf911
Revises: 8ffae68830a0
Create Date: 2025-12-16 07:41:06.438655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b2bbebabf911'
down_revision: Union[str, Sequence[str], None] = '8ffae68830a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('evaluations', sa.Column('artifact_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('evaluations', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('evaluations', sa.Column('deleted_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'evaluations', 'users', ['created_by'], ['id'])
    op.add_column('projects', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('deleted_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'deleted_by')
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'created_by')
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.drop_column('evaluations', 'deleted_by')
    op.drop_column('evaluations', 'deleted_at')
    op.drop_column('evaluations', 'artifact_hash')
    op.drop_column('evaluations', 'created_by')
    # ### end Alembic commands ###
