import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Sidebar configuration for Synth Studio Documentation.
 * Icons are applied via CSS using data-sidebar-icon attributes.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    // Generate the rest of the sidebar automatically from the docs folder structure
    {
      type: "autogenerated",
      dirName: ".", // Generate sidebar slice from the docs folder (or versioned_docs/<version>)
    },
  ],
};

export default sidebars;
